# fly.toml app configuration file generated for tvguide-ng on 2023-10-14T21:41:53+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tvguide-ng"
primary_region = "syd"

[processes]
worker = "python main.py"
web = "gunicorn api:app"

[env]
  PORT = 5000

[http_service]
  processes = ["web"]
  internal_port = 5000



[build]
  builder = "paketobuildpacks/builder:base"
