name: Deploy

on:
    push:
        branches:
            master


jobs:
    deploy:
        name: Deploy App
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4

            - name: Install Python dependencies
              run: pip install -r requirements.txt

            - name: Install Node Dependencies
              run: cd frontend && npm install

            - name: Build frontend
              run: cd frontend && npm run build
            
            - uses: superfly/flyctl-actions/setup-flyctl@master

            - name: Fly Deploy
              run: flyctl deploy --remote-only
              env:
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
