name: Tests

on:
  pull_request:
    branches:
      - develop

env:
  TVGUIDE_DB: ${{ secrets.TVGUIDE_DB }}
  PYTHON_ENV: testing
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}

jobs:
  Run-Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run backend tests
        run: python -m unittest -v

      - name: Run frontend tests
        run: cd frontend && npm run test