name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  TVGUIDE_DB: ${{ secrets.TVGUIDE_DB }}
  ENV: testing

jobs:
  Run-Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run test
        run: python -m unittest -v